"""empty message

Revision ID: 14bb5c1d1237
Revises: 
Create Date: 2023-02-15 15:02:43.845605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bb5c1d1237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fav__people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rel_people', sa.Integer(), nullable=True),
    sa.Column('rel_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rel_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['rel_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rel_planet', sa.Integer(), nullable=True),
    sa.Column('rel_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rel_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['rel_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__planet')
    op.drop_table('fav__people')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
