"""empty message

Revision ID: 9bb4578941a1
Revises: c68048fed206
Create Date: 2023-01-04 20:03:52.575150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb4578941a1'
down_revision = 'c68048fed206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fav__people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_name', sa.String(length=120), nullable=True),
    sa.Column('user_fav', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['people_name'], ['people.name'], ),
    sa.ForeignKeyConstraint(['user_fav'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=120), nullable=True),
    sa.Column('user_fav', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['planet_name'], ['planet.name'], ),
    sa.ForeignKeyConstraint(['user_fav'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__planet')
    op.drop_table('fav__people')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
